import { numero, pct, moeda } from '@/lib/formato.js';
import { fmtDuracao } from '@/lib/suporte.js';

const L = ({ itens }) => <div className="leitura">{itens.map(([r, v]) => <div key={r}><span>{r}</span><b>{v}</b></div>)}</div>;
export const Convites = ({ n }) => <L itens={[['Convidados', numero(n.convidados)], ['Aceitaram', numero(n.aceitaram)], ['Recusaram', numero(n.recusaram)], ['Sem resposta', numero(n.sem_resposta)], ['Adesão', pct(n.taxaAdesao)]]} />;
export const Validacao = ({ n }) => <L itens={[['Recebidas', numero(n.recebidas)], ['Válidas', numero(n.validas)], ['Inválidas', numero(n.invalidas)], ['Duplicadas', numero(n.duplicadas)], ['Telefone incorreto', numero(n.tel_incorreto)], ['Fora do perfil', numero(n.fora_perfil)], ['Aguardando', numero(n.pendentes)], ['Taxa de validação', pct(n.funil.validacao)]]} />;
export const AvisoInd = ({ n }) => <L itens={[['Avisados pelo aluno', numero(n.avisados)], ['Sem confirmação', numero(n.nao_confirmados)], ['Autorizaram', numero(n.autorizados)], ['Bloqueados', numero(n.bloqueados)], ['Taxa de aviso', pct(n.taxaAviso)]]} />;
export const Atendimento = ({ n }) => <L itens={[['Trabalhadas (tentativa)', numero(n.trabalhados)], ['Contato realizado', numero(n.responderam)], ['Validadas', numero(n.validadas)], ['Interesse identificado', numero(n.interesse)], ['Encaminhadas ao vendedor', numero(n.encaminhadas)], ['Em negociação', numero(n.negociacao)], ['Follow-ups', numero(n.followups)], ['Tempo até 1º contato', fmtDuracao(n.tempoPrimeiroContato)], ['Tempo até encaminhar', fmtDuracao(n.tempoAteEncaminhar)], ['Tempo até a venda', fmtDuracao(n.tempoAteVenda)], ['Sem 1ª tentativa no prazo', numero(n.semContato)], ['Paradas', numero(n.paradas)], ['Qualificadas sem vendedor', numero(n.semVendedor)]]} />;
export const Vendas = ({ n }) => <L itens={[['Vendas', numero(n.vendas)], ['Receita bruta', moeda(n.faturamento, 0)], ['Receita confirmada', moeda(n.recebido, 0)], ['Boletos/pagamentos pendentes', moeda(n.pendenteRecebimento, 0)], ['Canceladas/estornadas', numero(n.canceladas)], ['Cartão', moeda(n.cartao, 0)], ['PIX', moeda(n.pix, 0)], ['Boleto', moeda(n.boleto, 0)], ['Ticket médio', moeda(n.ticketMedio, 0)]]} />;
export const Funil = ({ n }) => <L itens={[['Adesão ao convite', pct(n.funil.adesao)], ['Taxa de contato', pct(n.funil.contato)], ['Taxa de validação', pct(n.funil.validacao)], ['Taxa de qualificação', pct(n.funil.qualificacao)], ['Conversão em venda', pct(n.funil.conversaoVenda)], ['Conversão geral', pct(n.funil.conversaoGeral)], ['Receita por indicação', moeda(n.funil.receitaPorRecebida, 0)], ['Follow-ups por venda', numero(n.funil.followupsPorVenda, 1)], ['% inválidas', pct(n.pctInvalidas)], ['% sem resposta', pct(n.pctSemResposta)]]} />;
export const Beneficios = ({ n }) => <L itens={[['Alunos indicadores', numero(n.indicadoresAtivos)], ['Indicações por aluno', numero(n.indicacoesPorAluno, 1)], ['Alunos com 5 validadas', numero(n.alunosCinco)], ['Pendentes', numero(n.beneficiosPendentes)], ['Sem escolha do aluno', numero(n.beneficiosSemEscolha)], ['Aprovados', numero(n.beneficiosAprovados)], ['Entregues', numero(n.beneficiosEntregues)], ['Atrasados', numero(n.beneficiosAtrasados)], ['Cashback pendente', moeda(n.cashbackPendente, 0)], ['Cashback pago', moeda(n.cashbackPago, 0)], ['Números de sorteio', numero(n.sorteios)], ['Custo dos benefícios', moeda(n.custo, 0)], ['Receita líquida estimada', moeda(n.funil.receitaLiquida, 0)]]} />;
