import { numero, pct, moeda } from '@/lib/formato.js';
import { fmtDuracao } from '@/lib/suporte.js';

const L = ({ itens }) => <div className="leitura">{itens.map(([r, v]) => <div key={r}><span>{r}</span><b>{v}</b></div>)}</div>;
export const Convites = ({ n }) => <L itens={[['Convidados', numero(n.convidados)], ['Aceitaram', numero(n.aceitaram)], ['Recusaram', numero(n.recusaram)], ['Sem resposta', numero(n.sem_resposta)], ['Adesão', pct(n.taxaAdesao)]]} />;
export const Validacao = ({ n }) => <L itens={[['Recebidas', numero(n.recebidas)], ['Válidas', numero(n.validas)], ['Inválidas', numero(n.invalidas)], ['Duplicadas', numero(n.duplicadas)], ['Telefone incorreto', numero(n.tel_incorreto)], ['Fora do perfil', numero(n.fora_perfil)], ['Aguardando', numero(n.pendentes)], ['Taxa de validação', pct(n.funil.validacao)]]} />;
export const AvisoInd = ({ n }) => <L itens={[['Avisados pelo aluno', numero(n.avisados)], ['Sem confirmação', numero(n.nao_confirmados)], ['Autorizaram', numero(n.autorizados)], ['Bloqueados', numero(n.bloqueados)], ['Taxa de aviso', pct(n.taxaAviso)]]} />;
export const Atendimento = ({ n }) => <L itens={[['Distribuídas', numero(n.distribuidas)], ['1º contato', numero(n.contatadas)], ['Tempo até 1º contato', fmtDuracao(n.tempoPrimeiroContato)], ['Tentativas', numero(n.tentativas)], ['Responderam', numero(n.responderam)], ['Conversas', numero(n.conversas)], ['Agendamentos', numero(n.agendamentos)], ['Propostas', numero(n.propostas)], ['Sem contato (total)', numero(n.semContato)], ['Paradas +3 dias', numero(n.paradas)]]} />;
export const Vendas = ({ n }) => <L itens={[['Vendas', numero(n.vendas)], ['Faturamento', moeda(n.faturamento, 0)], ['Aprovado', moeda(n.aprovado, 0)], ['Cartão', moeda(n.cartao, 0)], ['PIX', moeda(n.pix, 0)], ['Boleto', moeda(n.boleto, 0)], ['Recebido', moeda(n.recebido, 0)], ['Ticket médio', moeda(n.ticketMedio, 0)]]} />;
export const Funil = ({ n }) => <L itens={[['Adesão', pct(n.funil.adesao)], ['Validação', pct(n.funil.validacao)], ['Contato', pct(n.funil.contato)], ['Resposta', pct(n.funil.resposta)], ['Agendamento', pct(n.funil.agendamento)], ['Proposta', pct(n.funil.proposta)], ['Venda / válida', pct(n.funil.vendaSobreValida)], ['Venda / proposta', pct(n.funil.vendaSobreProposta)], ['Receita por válida', moeda(n.funil.receitaPorValida, 0)], ['Custo por venda', moeda(n.funil.custoPorVenda, 0)]]} />;
export const Beneficios = ({ n }) => <L itens={[['Alunos indicadores', numero(n.indicadoresAtivos)], ['Indicações por aluno', numero(n.indicacoesPorAluno, 1)], ['Pendentes', numero(n.beneficiosPendentes)], ['Aprovados', numero(n.beneficiosAprovados)], ['Entregues', numero(n.beneficiosEntregues)], ['Atrasados', numero(n.beneficiosAtrasados)], ['Cashback pendente', moeda(n.cashbackPendente, 0)], ['Cashback pago', moeda(n.cashbackPago, 0)], ['Números de sorteio', numero(n.sorteios)], ['Custo dos benefícios', moeda(n.custo, 0)], ['Receita líquida estimada', moeda(n.funil.receitaLiquida, 0)]]} />;
